/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  supply: {
    [k: string]: unknown;
  };
} | {
  transmute: {
    [k: string]: unknown;
  };
} | {
  update_admin: {
    new_admin: string;
    [k: string]: unknown;
  };
} | {
  withdraw: {
    coins: Coin[];
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  admin: string;
  in_denom: string;
  out_denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  admin: {
    [k: string]: unknown;
  };
} | {
  pool: {
    [k: string]: unknown;
  };
};
export interface AdminResponse {
  admin?: string | null;
}
export interface PoolResponse {
  pool: TransmuterPool;
}
export interface TransmuterPool {
  in_coin: Coin;
  out_coin_reserve: Coin;
}