/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { ExecuteMsg, Uint128, Coin, InstantiateMsg, QueryMsg, AdminResponse, PoolResponse, TransmuterPool, SharesResponse } from "./Transmuter.types";
export interface TransmuterReadOnlyInterface {
  contractAddress: string;
  pool: () => Promise<PoolResponse>;
  shares: ({
    address
  }: {
    address: string;
  }) => Promise<SharesResponse>;
}
export class TransmuterQueryClient implements TransmuterReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.pool = this.pool.bind(this);
    this.shares = this.shares.bind(this);
  }

  pool = async (): Promise<PoolResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pool: {}
    });
  };
  shares = async ({
    address
  }: {
    address: string;
  }): Promise<SharesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      shares: {
        address
      }
    });
  };
}
export interface TransmuterInterface extends TransmuterReadOnlyInterface {
  contractAddress: string;
  sender: string;
  joinPool: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  transmute: ({
    tokenOutDenom
  }: {
    tokenOutDenom: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  exitPool: ({
    tokensOut
  }: {
    tokensOut: Coin[];
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class TransmuterClient extends TransmuterQueryClient implements TransmuterInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.joinPool = this.joinPool.bind(this);
    this.transmute = this.transmute.bind(this);
    this.exitPool = this.exitPool.bind(this);
  }

  joinPool = async (fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      join_pool: {}
    }, fee, memo, funds);
  };
  transmute = async ({
    tokenOutDenom
  }: {
    tokenOutDenom: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      transmute: {
        token_out_denom: tokenOutDenom
      }
    }, fee, memo, funds);
  };
  exitPool = async ({
    tokensOut
  }: {
    tokensOut: Coin[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      exit_pool: {
        tokens_out: tokensOut
      }
    }, fee, memo, funds);
  };
}