/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./Transmuter.client";
export declare namespace contracts {
    const Transmuter: {
        TransmuterQueryClient: typeof _1.TransmuterQueryClient;
        TransmuterClient: typeof _1.TransmuterClient;
    };
}
//# sourceMappingURL=index.d.ts.map